---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: functions.py

container:
  image: apluslms/grade-python:math-3.9-4.4-4.0
  mount: assignments/summary_statistics
  cmd: graderutils